version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    working_directory: /tmp

commands:
  say_hello_command:
    description: A command that say's hello
    parameters:
      first:
        type: string
        default: "Some nigga said to do this"

      second:
        type: integer
        default: 200000

    steps:
    - run: echo << parameters.second >>
    - run: echo << parameters.first >>

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
    - say_hello_command
    - run: echo "Hello world is really getting boring shaa..." > output.txt
    - persist_to_workspace:
        root: ./
        paths:
        - output.txt

  print_output_file:
    executor: my-executor
    steps:
    - attach_workspace:
        at: ./
    - run: cat output.txt -e


workflows:
  this-workflow:
    jobs:
    - save_hello_world_output
    - print_output_file:
        requires: [save_hello_world_output]