version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-my-name:
    docker:
    - image: cimg/base:stable
    steps:
    - run: "echo My name is Osoraa Nwankwo!!!"

  print-env:
    docker:
    - image: cimg/base:stable
    steps:
    - run:
        name: "Osoraa"
        command: "echo $ME"

workflows:
  say-hello-workflow:
    jobs:
    - say-hello
    - say-my-name:
        requires:
          - say-hello
    - print-env:
        requires:
          - "say-my-name"
