version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    working_directory: /tmp

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
    - run: echo "Hello world is really getting boring shaa..." > output.txt
    - persist_to_workspace:
        root: .
        paths:
        - output.txt

  print_output_file:
    executor: my-executor
    steps:
    - attach_workspace:
        at: tmp
    - run: cat output.txt -e

workflows:
  this-workflow:
    jobs:
    - save_hello_world_output
    - print_output_file:
        requires:
          - save_hello_world_output